package query

const (
	UserEmail                    = "UserEmail"
	UserName                     = "UserDisplayName"
	UserId                       = "UserAppKey"
	UserTotalActiveTime          = "UserTipActiveSec"
	UserTotalTime                = "UserTipTotalSec"
	UserAverageSessionActiveTime = "UserTipAvgActiveSec"
	UserAverageSessionLength     = "UserTipAvgSessionSec"
	UserFirstSeen                = "UserCreated"
	UserTotalSessions            = "UserTipNumSessions"
	UserLastSeen                 = "UserTipLastSessionStart"
	UserReferrerUrl              = "PageRefererUrl"
	UserCity                     = "UserTipLastCity"
	UserStateRegion              = "PageRegion"
	UserCountry                  = "PageCountry"
	UserIpAddress                = "PageIp"
	UserDevice                   = "PageDevice"
	UserBrowser                  = "UserTipLastBrowser"
	UserUserAgent                = "UserTipLast"
	UserOperatingSystem          = "UserTipLastOperatingSystem"
	UserDisplayWidth             = "PageScreenWidth"
	UserDisplayHeight            = "PageScreenHeight"
)
